name: hijazi
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev



version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  nb_utils: ^4.6.16
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.1.0
  curved_navigation_bar:
  url_launcher: ^6.1.2
  permission_handler:
  image_picker:
  mobx: ^2.0.3
  flutter_mobx: ^2.0.1
  badges: ^2.0.3
  google_maps_flutter: ^2.5.0
  flutter_spinkit: ^5.2.0
  flutter_polyline_points: ^2.0.0
  location: ^5.0.3
  flutter_date_range_picker: ^0.0.14
  file_picker:
  cloudinary_public:
  http:
  share:
  dotted_border: ^2.1.0
  get:
  carousel_slider: ^4.1.1
  lottie:
  shared_preferences: ^2.0.15
  flutter_otp_text_field: ^1.1.1
  intl:
  flutter_form_builder: ^9.1.1
  flutter_dropdown:
  dartz: ^0.10.1
  flutter_rating_bar: ^4.0.1
  marquee:


dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.2
  build_runner: ^2.1.0
  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true


  assets:
    - assets/image/
    - assets/lottie/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo/Cairo-Bold.ttf
          weight: 700
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal/Tajawal-Bold.ttf
          weight: 700
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Black.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-BoldItalic.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-ExtraBold.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-ExtraBoldItalic.ttf
        - asset: assets/fonts/PlayfairDisplay/PlayfairDisplay-Italic.ttf
          weight: 700